
- name: Ensure Apache2 is installed
  apt:
    name:
      - apache2   
    state: latest
    
- name: Ensure required Apache2 modules are enabled
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - ssl
    - headers
    - rewrite
    - proxy
    - proxy_http
    
- name: Ensure rmfakecloud.conf is present
  template:
    src: "{{ role_path }}/templates/apache2/rmfakecloud.conf.j2"
    dest: "{{ rmfakecloud_apache2_path }}/sites-available/rmfakecloud.conf"
    mode: 0644
  notify: Ensure Apache2 recognizes config changes

- name: Ensure rmfakecloud.conf is enabled
  file:
    src: "{{ rmfakecloud_apache2_path }}/sites-available/rmfakecloud.conf"
    path: "{{ rmfakecloud_apache2_path }}/sites-enabled/rmfakecloud.conf"
    state: link
    mode: 0644
  notify: Ensure Apache2 recognizes config changes

- name: Flush handlers
  meta: flush_handlers

- name: Ensure rmfakecloud is accesable from host
  local_action:
    module: uri
    force: true
    url: "{{ rmfakecloud_storage_url }}"
    timeout: "{{ rmfakecloud_apache_timeout }}"
  
  

    
