---
- name: Check existence of rmfakecloud.service
  stat:
    path: "{{ rmfakecloud_systemd_path }}/rmfakecloud.service"
  register: rmfakecloud_service_stat

- name: Ensure rmfakecloud is stopped
  service:
    name: rmfakecloud
    state: stopped
  when: "rmfakecloud_service_stat.stat.exists"

- name: Ensure rmfakecloud_service_stat.service doesn't exist
  file:
    path: "{{ rmfakecloud_systemd_path }}/rmfakecloud.service"
    state: absent
  notify: Ensure systemd reloaded after service change installation

- name: Ensure rmfakecloud Docker image doesn't exist
  docker_image:
    name: "{{ rmfakecloud_docker_image }}"
    state: absent
